#include "ShaderBase.glsl"

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

void main()
{
    uvec3 cluster = gl_GlobalInvocationID.xyz;
    uvec3 dimensions = uvec3(clusterDimensions.xyz);
    if (any(greaterThanEqual(cluster, dimensions)))
    {
        return;
    }

    uint cluster_id =
        cluster.x + (cluster.y * dimensions.x) + (cluster.z * dimensions.x * dimensions.y);
    uint offset = cluster_id * TBX_MAX_LIGHTS_PER_CLUSTER;
    uint write_count = 0u;
    for (uint light_id = 0u; light_id < lightCount && write_count < TBX_MAX_LIGHTS_PER_CLUSTER;
         ++light_id)
    {
        lightIndexPool[offset + write_count] = light_id;
        ++write_count;
    }

    clusters[cluster_id].lightOffset = offset;
    clusters[cluster_id].lightCount = write_count;
}
