name: Windows Setup

description: Prepare Windows builds with sccache and caching.

inputs:
  sccache-dir:
    description: Path to the sccache directory.
    required: true
  cache-key:
    description: Cache key for the sccache cache.
    required: true
  cache-restore-keys:
    description: Restore keys for the sccache cache.
    required: false

runs:
  using: composite
  steps:
    - name: Set up sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Windows build cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.sccache-dir }}
        key: ${{ inputs.cache-key }}
        restore-keys: ${{ inputs.cache-restore-keys }}
