if(NOT DEFINED TBX_COMPILE_COMMANDS_SOURCE)
    message(FATAL_ERROR "TBX_COMPILE_COMMANDS_SOURCE is not set.")
endif()
if(NOT DEFINED TBX_COMPILE_COMMANDS_DESTINATION)
    message(FATAL_ERROR "TBX_COMPILE_COMMANDS_DESTINATION is not set.")
endif()

if(NOT EXISTS "${TBX_COMPILE_COMMANDS_SOURCE}")
    message(STATUS "compile_commands.json not found at ${TBX_COMPILE_COMMANDS_SOURCE}.")
    return()
endif()

if(WIN32)
    file(COPY_FILE
        "${TBX_COMPILE_COMMANDS_SOURCE}"
        "${TBX_COMPILE_COMMANDS_DESTINATION}"
        ONLY_IF_DIFFERENT
    )
else()
    if(EXISTS "${TBX_COMPILE_COMMANDS_DESTINATION}")
        file(REMOVE "${TBX_COMPILE_COMMANDS_DESTINATION}")
    endif()
    file(CREATE_LINK
        "${TBX_COMPILE_COMMANDS_SOURCE}"
        "${TBX_COMPILE_COMMANDS_DESTINATION}"
        SYMBOLIC
    )
endif()
