if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "generate_builtin_assets_header: OUTPUT_FILE is required")
endif()

if(NOT DEFINED SOURCE_ROOT)
    message(FATAL_ERROR "generate_builtin_assets_header: SOURCE_ROOT is required")
endif()

function(read_meta_id relative_meta_path out_id)
    set(meta_file "${SOURCE_ROOT}/${relative_meta_path}")
    if(NOT EXISTS "${meta_file}")
        message(FATAL_ERROR "generate_builtin_assets_header: missing meta file '${meta_file}'")
    endif()

    file(READ "${meta_file}" meta_text)
    string(JSON id_hex GET "${meta_text}" id)
    if("${id_hex}" STREQUAL "")
        message(FATAL_ERROR "generate_builtin_assets_header: missing id in '${meta_file}'")
    endif()

    string(TOUPPER "${id_hex}" id_hex_upper)
    set(${out_id} "${id_hex_upper}" PARENT_SCOPE)
endfunction()

read_meta_id("resources/Shaders/Globals.glsl.meta" globals_shader_library_id)
read_meta_id("resources/Shaders/DefaultLit.vert.meta" lit_vertex_shader_id)
read_meta_id("resources/Shaders/DefaultLit.frag.meta" lit_fragment_shader_id)
read_meta_id("resources/Materials/DefaultLit.mat.meta" lit_material_id)
read_meta_id("resources/Textures/NotFound.png.meta" not_found_texture_id)
read_meta_id("resources/Shaders/DefaultUnlit.vert.meta" unlit_vertex_shader_id)
read_meta_id("resources/Shaders/DefaultUnlit.frag.meta" unlit_fragment_shader_id)
read_meta_id("resources/Materials/DefaultUnlit.mat.meta" unlit_material_id)
read_meta_id("resources/Shaders/DeferredGeometry.vert.meta" deferred_geometry_vertex_shader_id)
read_meta_id("resources/Shaders/DeferredGeometry.frag.meta" deferred_geometry_fragment_shader_id)
read_meta_id("resources/Shaders/DeferredLighting.vert.meta" deferred_lighting_vertex_shader_id)
read_meta_id("resources/Shaders/DeferredLighting.frag.meta" deferred_lighting_fragment_shader_id)
read_meta_id("resources/Materials/DeferredLighting.mat.meta" deferred_lighting_material_id)
read_meta_id("resources/Icons/Box.png.meta" box_icon_id)

set(content "")
string(APPEND content "#pragma once\n")
string(APPEND content "#include \"tbx/common/handle.h\"\n\n")
string(APPEND content "namespace tbx\n")
string(APPEND content "{\n")
string(APPEND content "    inline const Handle globals_shader_library = Handle(Uuid(0x${globals_shader_library_id}U));\n")
string(APPEND content "    inline const Handle lit_vertex_shader = Handle(Uuid(0x${lit_vertex_shader_id}U));\n")
string(APPEND content "    inline const Handle lit_fragment_shader = Handle(Uuid(0x${lit_fragment_shader_id}U));\n")
string(APPEND content "    inline const Handle lit_material = Handle(Uuid(0x${lit_material_id}U));\n")
string(APPEND content "    inline const Handle not_found_texture = Handle(Uuid(0x${not_found_texture_id}U));\n")
string(APPEND content "    inline const Handle unlit_vertex_shader = Handle(Uuid(0x${unlit_vertex_shader_id}U));\n")
string(APPEND content "    inline const Handle unlit_fragment_shader = Handle(Uuid(0x${unlit_fragment_shader_id}U));\n")
string(APPEND content "    inline const Handle unlit_material = Handle(Uuid(0x${unlit_material_id}U));\n")
string(APPEND content "    inline const Handle default_shader = lit_vertex_shader;\n")
string(APPEND content "    inline const Handle deferred_geometry_vertex_shader = Handle(Uuid(0x${deferred_geometry_vertex_shader_id}U));\n")
string(APPEND content "    inline const Handle deferred_geometry_fragment_shader = Handle(Uuid(0x${deferred_geometry_fragment_shader_id}U));\n")
string(APPEND content "    inline const Handle deferred_lighting_vertex_shader = Handle(Uuid(0x${deferred_lighting_vertex_shader_id}U));\n")
string(APPEND content "    inline const Handle deferred_lighting_fragment_shader = Handle(Uuid(0x${deferred_lighting_fragment_shader_id}U));\n")
string(APPEND content "    inline const Handle deferred_lighting_material = Handle(Uuid(0x${deferred_lighting_material_id}U));\n")
string(APPEND content "    inline const Handle default_material = lit_material;\n")
string(APPEND content "    inline const Handle box_icon = Handle(Uuid(0x${box_icon_id}U));\n")
string(APPEND content "}\n")

cmake_path(GET OUTPUT_FILE PARENT_PATH output_directory)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT_FILE}" "${content}")
