if(NOT DEFINED TBX_WORKING_DIRECTORY_PATH)
  set(TBX_WORKING_DIRECTORY_PATH "")
endif()

if(NOT DEFINED TBX_LOGS_DIRECTORY_PATH)
  set(TBX_LOGS_DIRECTORY_PATH "")
endif()

if(NOT DEFINED TBX_RESOURCES_PATH)
  if(NOT TBX_FULL_RELEASE AND IS_DIRECTORY "${CMAKE_SOURCE_DIR}/resources")
    set(TBX_RESOURCES_PATH "${CMAKE_SOURCE_DIR}/resources")
  else()
    set(TBX_RESOURCES_PATH "")
  endif()
endif()

add_compile_definitions(
  $<$<CONFIG:Debug>:TBX_DEBUG>
  $<$<CONFIG:Release>:TBX_RELEASE>
  TBX_WORKING_DIRECTORY="${TBX_WORKING_DIRECTORY_PATH}"
  TBX_LOGS_DIRECTORY="${TBX_LOGS_DIRECTORY_PATH}"
  TBX_RESOURCES_PATH="${TBX_RESOURCES_PATH}"
  $<$<CONFIG:Debug>:TBX_ASSERTS_ENABLED>
  $<$<PLATFORM_ID:Windows>:TBX_PLATFORM_WINDOWS>
  $<$<PLATFORM_ID:Darwin>:TBX_PLATFORM_MACOS>
  $<$<PLATFORM_ID:Linux>:TBX_PLATFORM_LINUX>
)
