name: Auto assign issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to author
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue
          github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue.number,
            assignees: [issue.user.login],
          })
